main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('add_kegiatan/', views.add_kegiatan, name='add_kegiatan'),
    path('daftar_kegiatan/<int:id>', views.daftar_kegiatan, name='daftar')
]

story_6/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
class Kegiatan(models.Model):
    title = models.CharField(max_length=30)
    desc = models.CharField(max_length=255, default='')
    date = models.DateTimeField(default=timezone.now, blank=True)
    class Meta:
        # Pengurutan berdasarkan judul
        ordering = ['date']
    
    def __str__(self):
        return self.title

class Person(models.Model):
    nama = models.CharField(max_length=100)
    kegiatan = models.ManyToManyField(Kegiatan)

    class Meta:
        # Pengurutan berdasarkan nama
        ordering = ['nama']

    def __str__(self):
        return self.nama

main/forms.py
from django import forms
from .models import Kegiatan, Person


class KegiatanForm(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = ['title','desc','date']
        
    my_widget = forms.TextInput(attrs={'class':'form-control', 'spellcheck':'false'})
    title = forms.CharField(widget=my_widget, max_length=30)
    desc = forms.CharField(widget=my_widget, max_length=255)
    date_widget = forms.DateTimeInput(
        attrs= {
            'class' : 'form-control datetimepicker-input',
            'data-target' :'#datetimepicker1'
        }
    )
    date = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], widget=forms.DateTimeInput()) 

main/views.py
from django.shortcuts import render, redirect
from .models import Kegiatan, Person
from .forms import KegiatanForm
from datetime import datetime

def home(request):
    data = {
        'kegiatans' : Kegiatan.objects.all(),
        'form' : KegiatanForm,
    }
    return render(request, 'main/home.html', data)

def add_kegiatan(request):
    form = KegiatanForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('main:home')
    return redirect('main:home')

def daftar_kegiatan(request, id):
    if request.method == 'POST':
        kegiatan = Kegiatan.objects.get(id=id)
        person = Person.objects.get_or_create(
            nama=request.POST['daftar']
        )
        person[0].kegiatan.add(kegiatan)
        return redirect('main:home')
    return redirect('main:home')

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
<link rel="stylesheet" href="{% static 'css/story6.css' %}">
{% endblock meta %}

{% block content %}
<div class="my-form">
  <form action="{% url 'main:add_kegiatan' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="id_title">Nama Kegiatan</label>
      {{ form.title }}
    </div>
    <div class="form-group">
      <label for="id_desc">Deskripsi Kegiatan</label>
      {{ form.desc }}
    </div>
    <div class="form-group">
      <label for="id_title">Jadwal Kegiatan</label>
      <div class="input-group date coba" id="datetimepicker1" data-target-input="nearest">
        {{ form.date }}
        <div class="input-group-append x" data-target="#datetimepicker1" data-toggle="datetimepicker">
          <div class="input-group-text"><i class="fa fa-calendar"></i></div>
        </div>
    </div>
    </div>
    <div class="sub">
      <input type="submit" value="Submit">
    </div>
  </form>
</div>

<div class="container-fluid list">
  <h3>Daftar Kegiatan</h3>
  <div class="row flex-row flex-nowrap">
    {% for kegiatan in kegiatans %}
    <div class="col-5">
        <div class="card text-white bg-dark mb-3 cust-card">
          <div class="card-header">{{ kegiatan.title }}</div>
          <div class="card-body item-{{ forloop.counter }}">
            <div class="cust-body-{{ forloop.counter }} d-flex flex-column justify-content-between content-card">
              <h5 class="card-title">{{ kegiatan.date.day }}-{{ kegiatan.date.month }}-{{ kegiatan.date.year }} {{ kegiatan.date.hour }}:{{ kegiatan.date.minute }}</h5>
              <p class="card-text">Deskripsi: </p>
              <ul class="list-group">
                {% for person in kegiatan.person_set.all %}
                <li class="list-group-item bg-dark cust-li">{{ person.nama }}</li>
                {% endfor %}
              </ul>
              <button type="button" class="btn btn-dark cust-btn-{{ forloop.counter }}">Tambah Peserta</button>
              
            </div>

            <div class="cust-daftar-{{ forloop.counter }} clicked">
              <i class="fa fa-arrow-left back-{{ forloop.counter }}"></i>
              <form action="{% url 'main:daftar' kegiatan.id %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                  <label for="daftar-kegiatan">Nama</label>
                  <input type="text" name="daftar" id="daftar-kegiatan" class="form-control" spellcheck="false">
                </div>
                <input type="submit" value="Daftar" class="daftar-btn">
              </form>
            </div>
            
          </div>
        </div>
    </div>

    <script>
      $('.cust-btn-{{ forloop.counter }}').on('click', function () {
      $('.cust-body-{{ forloop.counter }}').addClass('clicked');
      $('.cust-body-{{ forloop.counter }}').removeClass('d-flex');
      $('.cust-daftar-{{ forloop.counter }}').removeClass('clicked');
  });


  $('.back-{{ forloop.counter }}').on('click', function () {
    $('.cust-body-{{ forloop.counter }}').removeClass('clicked');
    $('.cust-body-{{ forloop.counter }}').addClass('d-flex');
    $('.cust-daftar-{{ forloop.counter }}').addClass('clicked');
  });
  </script>
    {% endfor %}
  </div>
</div>

  <script type="text/javascript">
    $(function () {
        $('#datetimepicker1').datetimepicker({
          format: 'DD/MM/YYYY HH:mm',
        });
    });
</script>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Bootstrap 4 -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

  <!-- Font Awesome -->
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  <!-- Moment.js -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

  <!-- Tempus Dominus Bootstrap 4 -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>

<link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>